-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 13:56:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rh_Empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rh_Empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rh_Empresa` DEFAULT CHARACTER SET utf8 ;
USE `rh_Empresa` ;

-- -----------------------------------------------------
-- Table `rh_Empresa`.`rh_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rh_Empresa`.`rh_Empresa` (
  `idrh_Empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`idrh_Empresa`),
  UNIQUE INDEX `idrh_Empresa_UNIQUE` (`idrh_Empresa` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO rh_Empresa (nome, sobrenome, cargo, data_admissao, salario)
values ("Alfredo","Souza", "Assistente", "2020/08/25", 1500.00),
("Liz", "Anja", "Gerente", "2020/05/14", 4000.00),
("Isac", "Anjo", "SubGerente", "2020/07/10", 3000.00),
("Victor", "Augusto", "Assistente", "2020/11/23", 1500.00);

SELECT * FROM rh_empresa.rh_Empresa;

SELECT * FROM rh_Empresa WHERE salario > 2000.00;
SELECT * FROM rh_Empresa WHERE salario < 2000.00;

UPDATE rh_empresa.rh_Empresa
SET salario = 3400.00 WHERE idrh_Empresa = 3;