-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 19:55:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`tb_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`tb_alunos` (
  `id_alunos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `turma` VARCHAR(10) NOT NULL,
  `nota` FLOAT NOT NULL,
  PRIMARY KEY (`id_alunos`),
  UNIQUE INDEX `id_alunos_UNIQUE` (`id_alunos` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM escola.tb_alunos;

INSERT INTO tb_alunos (nome, sobrenome, idade, turma, nota)
values("João","Gustavo",15,"1ºA",7),
("Vitoria","Silva",15,"1ºA",6),
("Pablo","Arruda",16,"2ºA",9),
("Gabriela","Gouveia",16,"2ºA",10),
("Iago","Siqueira",17,"3ºA",4),
("Amanda","Souza",17,"3ºA",5);

SELECT * FROM tb_alunos WHERE nota >= 7;
SELECT * FROM tb_alunos WHERE nota < 7;

UPDATE escola.tb_alunos
SET turma = "3ºB" WHERE id_alunos = 6;